### ISSUE TITLE
support for macOS hosted?

### ISSUE THREAD

**Issue by lilMango** [wzieba/Firebase-Distribution-Github-Action#13]
Hi,
I was just trying to upload my *.ipa file to the Firebase Distribution. (Added all TOKENS, and APP _ID)
My github actions are running on a macos hosted box and are getting the following error:
-  ##[error]Container action is only supported on Linux  

Am I missing a configuration, or is the MacOS hosted box just not supported for this plugin?

**Comment by lilMango** [comment]
Realized I could just call Firebase CLI to deploy it from my github script

**Comment by mohdabbas378** [comment]
I am getting this same error. What's the solution to this?

**Comment by wzieba** [comment]
You can build your *.ipa file in one job (MacOS hosted) and send it to another one (e.g. Linux hosted) and use this action there.

See more:
- [upload-artifact action](https://github.com/actions/upload-artifact)
- [download-artifact action](https://github.com/actions/download-artifact)

**Comment by mvn-tony-hn** [comment]
@wzieba I tried to upload & download my ipa file (around more than 20mb) by using upload&download-artifact action. But when upload to firebase distribution I always get the error below:
`Error: failed to upload release. There's been an error processing your app. Ensure you are uploading a valid IPA and try again. If this problem continues, contact Firebase support.`
I guess there is problem downloading file because when i try to download ipa file from the artifact on github action console and upload to firebase. It works with no problem. Do you have any suggestions for this case?

**Comment by RafaRuiz** [comment]
Same problem than ☝️
