### ISSUE TITLE
Invalid APK

### ISSUE THREAD

**Issue by Abhimanyu14** [wzieba/Firebase-Distribution-Github-Action#43]
Getting the following error when I try to distribute my app.
```
Error: failed to upload distribution. error processing your binary: There's been an error processing your distribution. 
Ensure you are uploading a valid IPA or APK and try again.
Additional information about this error:
Invalid APK file. (Code: INVALID_ZIP)
```

JOB 
```
# Upload apk file to firebase app distribution
      - name: upload artifact to firebase app distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: default
          file: app/build/outputs/apk/debug/app-debug.apk
          debug: true
```

**Comment by ShehanRashmika** [comment]
Hello!

did you solve this issue?

**Comment by Abhimanyu14** [comment]
> Hello!
> 
> did you solve this issue?

Nope

**Comment by wzieba** [comment]
Hi, I've just run a test and it seems that [the action is working correctly](https://github.com/wzieba/Firebase-Distribution-Github-Action/runs/2988660388?check_suite_focus=true). 

The message you receive is from [`Firebase CLI`](https://github.com/firebase/firebase-tools) - this Github Action is just a wrapper.

I believe that the `apk` you're trying to upload is either malformed or doesn't exist - could you please confirm (maybe with `ls`ing the directory after build) that `apk` is in `app/build/outputs/apk/debug/` directory?

**Comment by gianebinotto** [comment]
Hey! Have you solved this issue?

**Comment by wzieba** [comment]
Here's similar issue I've found on `firebase-tools` repository https://github.com/firebase/firebase-tools/issues/3555

The reason for this issue was, citing: 
> Looks like the error was due to invalid path name to the IPA

Please make sure the file is in the path you provide to the action.

For the future I've created an issue which might help for similar cases.

---

@gianebinotto 👋 

> Which version are you using?

The tests I've performed where from [`master` branch](https://github.com/wzieba/Firebase-Distribution-Github-Action/blob/master/.github/workflows/main.yml#L8) but they basically are even with `v1` tag (they point to the same commit)

**Comment by ShehanRashmika** [comment]
My APK path was wrong. Just try to identify the correct path using **ls** cmd.

**Comment by gianebinotto** [comment]
I could solve adjusting the path as well, thank you guys!
